version: "3"
services:
  train:
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: qqwenet_context-train:latest
    command: /bin/sh -c "while sleep infinity; do :; done"
    volumes:
      - ./:/home/homework/s0
      - /nfs-speech-cfs:/nfs-speech-cfs
      # - /mnt/nfs_share_speech3:/mnt/nfs_share_speech3
      # - /data:/data
    shm_size: '1gb'
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: 'compute,video,utility'
    privileged: true
    network_mode: host
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    cap_add:
      - "IPC_LOCK"
      - "SYS_PTRACE" # allow gdb
